# Workflow derived from https://github.com/r-lib/actions/tree/master/examples and edited by me (Dennis)
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on: 
  pull_request:
  workflow_dispatch:

name: Test build of pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: pkgdown, roxygen2
          needs: website

      - name: Deploy package 1
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'roxygen2::roxygenise()'
          
      - name: Deploy package 2
        run: Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, branch = "gh-pages-test")'
         
